'use strict';
export const USER_INFO = 'USER_INFO';

export const LOCATION = 'LOCATION';
export const LOCATION_BACK = 'LOCATION_BACK';

export const INFLUXDB_ADD_SERVER = 'INFLUXDB_ADD_SERVER';
export const INFLUXDB_LIST_SERVER = 'INFLUXDB_LIST_SERVER';
export const INFLUXDB_EDIT_SERVER = 'INFLUXDB_EDIT_SERVER';
export const INFLUXDB_REMOVE_SERVER = 'INFLUXDB_REMOVE_SERVER';
export const INFLUXDB_LIST_DATABASE = 'INFLUXDB_LIST_DATABASE';
