'use strict';
export const USER_INFO = 'USER_INFO';

export const LOCATION = 'LOCATION';
export const LOCATION_BACK = 'LOCATION_BACK';

export const INFLUXDB_LIST_DATABASE = 'INFLUXDB_LIST_DATABASE';
export const INFLUXDB_LIST_RP = 'INFLUXDB_LIST_RP';
export const INFLUXDB_LIST_MEASUREMENT = 'INFLUXDB_LIST_MEASUREMENT';
export const INFLUXDB_LIST_TAG_INFO = 'INFLUXDB_LIST_TAG_INFO';
export const INFLUXDB_LIST_FIELDS = 'INFLUXDB_LIST_FIELDS';

export const SERVER_ADD = 'SERVER_ADD';
export const SERVER_LIST = 'SERVER_LIST';
export const SERVER_EDIT = 'SERVER_EDIT';
export const SERVER_REMOVE = 'SERVER_REMOVE';

export const CONFIGURE_LIST = 'CONFIGURE_LIST';
export const CONFIGURE_ADD = 'CONFIGURE_ADD';
export const CONFIGURE_UPDATE = 'CONFIGURE_UPDATE';
export const CONFIGURE_REMOVE = 'CONFIGURE_REMOVE';

export const DASHBOARD_ADD = 'DASHBOARD_ADD';
export const DASHBOARD_LIST = 'DASHBOARD_LIST';
export const DASHBOARD_REMOVE = 'DASHBOARD_REMOVE';
export const DASHBOARD_UPDATE = 'DASHBOARD_UPDATE';
