'use strict';
export const USER_INFO = 'USER_INFO';

export const LOCATION = 'LOCATION';
export const LOCATION_BACK = 'LOCATION_BACK';

export const INFLUXDB_ADD_SERVER = 'INFLUXDB_ADD_SERVER';
export const INFLUXDB_LIST_SERVER = 'INFLUXDB_LIST_SERVER';
export const INFLUXDB_EDIT_SERVER = 'INFLUXDB_EDIT_SERVER';
export const INFLUXDB_REMOVE_SERVER = 'INFLUXDB_REMOVE_SERVER';
export const INFLUXDB_LIST_DATABASE = 'INFLUXDB_LIST_DATABASE';
export const INFLUXDB_LIST_RP = 'INFLUXDB_LIST_RP';
export const INFLUXDB_LIST_MEASUREMENT = 'INFLUXDB_LIST_MEASUREMENT';
export const INFLUXDB_LIST_TAG_INFO = 'INFLUXDB_LIST_TAG_INFO';
export const INFLUXDB_LIST_FIELDS = 'INFLUXDB_LIST_FIELDS';
export const INFLUXDB_LIST_CONFIGURE = 'INFLUXDB_LIST_CONFIGURE';
export const INFLUXDB_ADD_CONFIGURE = 'INFLUXDB_ADD_CONFIGURE';
export const INFLUXDB_UPDATE_CONFIGURE = 'INFLUXDB_UPDATE_CONFIGURE';
export const INFLUXDB_REMOVE_CONFIGURE = 'INFLUXDB_REMOVE_CONFIGURE';
export const INFLUXDB_ADD_DASHBOARD = 'INFLUXDB_ADD_DASHBOARD';
